server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://logs-prod-020.grafana.net/loki/api/v1/push
    basic_auth:
      username: "1665378"
      password: "[DÁN_TOKEN_CỦA_BẠN_VÀO_ĐÂY]"

scrape_configs:
  - job_name: ecommerce-file-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ecommerce-v1
          env: development
          __path__: /var/log/backend_logs/app.log