name: SonarQube Quality Check

on:
  push:
    branches:
      - develop

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          cd backend
          npm install

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: backend
          args: >
            -Dsonar.projectKey=Techmart-multi-branch-ecommerce
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**,dist/**,build/**